import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(fileURLToPath(import.meta.url), '../../');

// GITHUB_API_URL is set by GitHub Actions and lets this point at GHES.
const API = process.env.GITHUB_API_URL ?? 'https://api.github.com';

function git(...args: string[]): string {
  return execFileSync('git', args, { cwd: root, encoding: 'utf-8' }).trim();
}

/** Resolves origin's default branch, so the PR targets the right base. */
function defaultBranch(): string {
  try {
    return git('symbolic-ref', '--quiet', 'refs/remotes/origin/HEAD').replace(
      'refs/remotes/origin/',
      '',
    );
  } catch {
    return 'master';
  }
}

async function github(token: string, method: string, url: string, body: unknown): Promise<Response> {
  return fetch(`${API}${url}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });
}

function buildBody(name: string, description: string): string {
  return [
    `## @outbreak/${name}`,
    '',
    description,
    '',
    '### Checklist',
    '- [ ] Types look correct',
    '- [ ] README is accurate',
    '- [ ] Tests pass',
    '',
    '---',
    '_Generated by Outbreak_',
  ].join('\n');
}

/**
 * Commits the generated package on its own branch and opens a PR through the
 * REST API. Uses GITHUB_TOKEN/GITHUB_REPO directly rather than shelling out to
 * `gh`, so the pipeline has no external CLI dependency and the PR body keeps
 * its line breaks.
 */
export async function createPR(name: string, description: string): Promise<string> {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPO;
  if (!token || !repo) {
    throw new Error('GITHUB_TOKEN and GITHUB_REPO must be set (see .env.example)');
  }

  const branch = `sdk/add-${name}`;
  const base = defaultBranch();

  // -B so regenerating an existing package restarts the branch from HEAD
  // instead of stacking onto a stale attempt.
  git('checkout', '-B', branch);
  git('add', '--', `packages/${name}`);

  if (!git('status', '--porcelain', '--', `packages/${name}`)) {
    throw new Error(`No changes staged under packages/${name} — nothing to open a PR for`);
  }

  git('commit', '-m', `feat: add @outbreak/${name} SDK`);
  // The branch is owned by this generator, so a regenerated package may
  // legitimately replace what was pushed before.
  git('push', '--force-with-lease', '-u', 'origin', branch);

  const created = await github(token, 'POST', `/repos/${repo}/pulls`, {
    title: `Add @outbreak/${name} SDK`,
    head: branch,
    base,
    body: buildBody(name, description),
  });

  if (!created.ok) {
    throw new Error(`Failed to create PR: ${created.status} ${await created.text()}`);
  }

  const pr = (await created.json()) as { number: number; html_url: string };

  // A missing "sdk" label must not fail a run that already produced a PR.
  const labelled = await github(token, 'POST', `/repos/${repo}/issues/${pr.number}/labels`, {
    labels: ['sdk'],
  });
  if (!labelled.ok) {
    console.log(`      could not add the "sdk" label (${labelled.status}); continuing`);
  }

  return pr.html_url;
}
