import { execSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(fileURLToPath(import.meta.url), '../../');
const opts = { cwd: root, stdio: 'inherit' as const };

export function createPR(name: string, description: string): void {
  const branch = `sdk/add-${name}`;

  try {
    execSync(`git checkout -b ${branch}`, opts);
  } catch {
    // Branch may already exist; check it out
    execSync(`git checkout ${branch}`, opts);
  }

  execSync(`git add packages/${name}`, opts);
  execSync(`git commit -m "feat: add @outbreak/${name} SDK"`, opts);
  execSync(`git push -u origin ${branch}`, opts);

  execSync(
    `gh pr create \
      --title "Add @outbreak/${name} SDK" \
      --body "## @outbreak/${name}\n\n${description}\n\n### Checklist\n- [ ] Types look correct\n- [ ] README is accurate\n- [ ] Tests pass\n\n---\n_Generated by Outbreak_" \
      --label "sdk"`,
    opts,
  );
}
